name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credentials file
      env:
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
      run: |
        echo "$BIGQUERY_CREDENTIALS" > /tmp/bigquery_credentials.json

    - name: Deploy to Streamlit
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/bigquery_credentials.json
      run: |
        streamlit run app.py

